services:
  pgdatabase:
    image: postgres:13
    environment:
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=root
      - POSTGRES_DB=ny_taxi
    volumes:
      - "/Users/stealth_shadow/Applications/dbs/postgres/ny_taxi_postgres_data:/var/lib/postgresql/data:rw"
    ports:
      - "5433:5432"
  pgadmin:
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=admin@admin.com
      - PGADMIN_DEFAULT_PASSWORD=root
    volumes:
      - "/Users/stealth_shadow/Applications/dbs/postgres/data_pgadmin:/var/lib/pgadmin:rw"  
    ports:
      - "8080:80"
  jupyter:
    image: jupyter/scipy-notebook:lab-4.0.7
    volumes:
      - "/Users/stealth_shadow/Applications/dbs/jupyter/work:/home/jovyan/work:rw"  
    ports:
      - "8889:8888"
